# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import books_pb2 as books__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.is_book = channel.unary_unary(
                '/booksservice.BooksService/is_book',
                request_serializer=books__pb2.IsBookRequest.SerializeToString,
                response_deserializer=books__pb2.IsBookResponse.FromString,
                _registered_method=True)
        self.is_book_by_name = channel.unary_unary(
                '/booksservice.BooksService/is_book_by_name',
                request_serializer=books__pb2.IsBookByNameRequest.SerializeToString,
                response_deserializer=books__pb2.IsBookResponse.FromString,
                _registered_method=True)
        self.get_book_by_id = channel.unary_unary(
                '/booksservice.BooksService/get_book_by_id',
                request_serializer=books__pb2.GetBookByIdRequest.SerializeToString,
                response_deserializer=books__pb2.Book.FromString,
                _registered_method=True)
        self.get_book_by_name = channel.unary_unary(
                '/booksservice.BooksService/get_book_by_name',
                request_serializer=books__pb2.GetBookByNameRequest.SerializeToString,
                response_deserializer=books__pb2.Book.FromString,
                _registered_method=True)
        self.all_books = channel.unary_unary(
                '/booksservice.BooksService/all_books',
                request_serializer=books__pb2.EmptyObject.SerializeToString,
                response_deserializer=books__pb2.AllBooksResponse.FromString,
                _registered_method=True)
        self.add_book = channel.unary_unary(
                '/booksservice.BooksService/add_book',
                request_serializer=books__pb2.Book.SerializeToString,
                response_deserializer=books__pb2.EmptyObject.FromString,
                _registered_method=True)
        self.update_book = channel.unary_unary(
                '/booksservice.BooksService/update_book',
                request_serializer=books__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=books__pb2.EmptyObject.FromString,
                _registered_method=True)
        self.delete_book = channel.unary_unary(
                '/booksservice.BooksService/delete_book',
                request_serializer=books__pb2.Book.SerializeToString,
                response_deserializer=books__pb2.EmptyObject.FromString,
                _registered_method=True)


class BooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def is_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_book_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_book_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_book_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def all_books(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'is_book': grpc.unary_unary_rpc_method_handler(
                    servicer.is_book,
                    request_deserializer=books__pb2.IsBookRequest.FromString,
                    response_serializer=books__pb2.IsBookResponse.SerializeToString,
            ),
            'is_book_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.is_book_by_name,
                    request_deserializer=books__pb2.IsBookByNameRequest.FromString,
                    response_serializer=books__pb2.IsBookResponse.SerializeToString,
            ),
            'get_book_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_book_by_id,
                    request_deserializer=books__pb2.GetBookByIdRequest.FromString,
                    response_serializer=books__pb2.Book.SerializeToString,
            ),
            'get_book_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_book_by_name,
                    request_deserializer=books__pb2.GetBookByNameRequest.FromString,
                    response_serializer=books__pb2.Book.SerializeToString,
            ),
            'all_books': grpc.unary_unary_rpc_method_handler(
                    servicer.all_books,
                    request_deserializer=books__pb2.EmptyObject.FromString,
                    response_serializer=books__pb2.AllBooksResponse.SerializeToString,
            ),
            'add_book': grpc.unary_unary_rpc_method_handler(
                    servicer.add_book,
                    request_deserializer=books__pb2.Book.FromString,
                    response_serializer=books__pb2.EmptyObject.SerializeToString,
            ),
            'update_book': grpc.unary_unary_rpc_method_handler(
                    servicer.update_book,
                    request_deserializer=books__pb2.UpdateBookRequest.FromString,
                    response_serializer=books__pb2.EmptyObject.SerializeToString,
            ),
            'delete_book': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_book,
                    request_deserializer=books__pb2.Book.FromString,
                    response_serializer=books__pb2.EmptyObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booksservice.BooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booksservice.BooksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def is_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/is_book',
            books__pb2.IsBookRequest.SerializeToString,
            books__pb2.IsBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_book_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/is_book_by_name',
            books__pb2.IsBookByNameRequest.SerializeToString,
            books__pb2.IsBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_book_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/get_book_by_id',
            books__pb2.GetBookByIdRequest.SerializeToString,
            books__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_book_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/get_book_by_name',
            books__pb2.GetBookByNameRequest.SerializeToString,
            books__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def all_books(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/all_books',
            books__pb2.EmptyObject.SerializeToString,
            books__pb2.AllBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/add_book',
            books__pb2.Book.SerializeToString,
            books__pb2.EmptyObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/update_book',
            books__pb2.UpdateBookRequest.SerializeToString,
            books__pb2.EmptyObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksservice.BooksService/delete_book',
            books__pb2.Book.SerializeToString,
            books__pb2.EmptyObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
