# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import borrow_pb2 as borrow__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in borrow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BorrowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.is_borrowed = channel.unary_unary(
                '/borrowservice.BorrowService/is_borrowed',
                request_serializer=borrow__pb2.IsBorrowedRequest.SerializeToString,
                response_deserializer=borrow__pb2.IsBorrowedResponse.FromString,
                _registered_method=True)
        self.is_borrowed_by = channel.unary_unary(
                '/borrowservice.BorrowService/is_borrowed_by',
                request_serializer=borrow__pb2.IsBorrowedByRequest.SerializeToString,
                response_deserializer=borrow__pb2.IsBorrowedResponse.FromString,
                _registered_method=True)
        self.borrow = channel.unary_unary(
                '/borrowservice.BorrowService/borrow',
                request_serializer=borrow__pb2.BorrowRequest.SerializeToString,
                response_deserializer=borrow__pb2.EmptyObject.FromString,
                _registered_method=True)
        self.return_book = channel.unary_unary(
                '/borrowservice.BorrowService/return_book',
                request_serializer=borrow__pb2.ReturnRequest.SerializeToString,
                response_deserializer=borrow__pb2.EmptyObject.FromString,
                _registered_method=True)


class BorrowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def is_borrowed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_borrowed_by(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def borrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def return_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BorrowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'is_borrowed': grpc.unary_unary_rpc_method_handler(
                    servicer.is_borrowed,
                    request_deserializer=borrow__pb2.IsBorrowedRequest.FromString,
                    response_serializer=borrow__pb2.IsBorrowedResponse.SerializeToString,
            ),
            'is_borrowed_by': grpc.unary_unary_rpc_method_handler(
                    servicer.is_borrowed_by,
                    request_deserializer=borrow__pb2.IsBorrowedByRequest.FromString,
                    response_serializer=borrow__pb2.IsBorrowedResponse.SerializeToString,
            ),
            'borrow': grpc.unary_unary_rpc_method_handler(
                    servicer.borrow,
                    request_deserializer=borrow__pb2.BorrowRequest.FromString,
                    response_serializer=borrow__pb2.EmptyObject.SerializeToString,
            ),
            'return_book': grpc.unary_unary_rpc_method_handler(
                    servicer.return_book,
                    request_deserializer=borrow__pb2.ReturnRequest.FromString,
                    response_serializer=borrow__pb2.EmptyObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'borrowservice.BorrowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('borrowservice.BorrowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BorrowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def is_borrowed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowservice.BorrowService/is_borrowed',
            borrow__pb2.IsBorrowedRequest.SerializeToString,
            borrow__pb2.IsBorrowedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_borrowed_by(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowservice.BorrowService/is_borrowed_by',
            borrow__pb2.IsBorrowedByRequest.SerializeToString,
            borrow__pb2.IsBorrowedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def borrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowservice.BorrowService/borrow',
            borrow__pb2.BorrowRequest.SerializeToString,
            borrow__pb2.EmptyObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def return_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/borrowservice.BorrowService/return_book',
            borrow__pb2.ReturnRequest.SerializeToString,
            borrow__pb2.EmptyObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
