# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: borrow.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'borrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62orrow.proto\x12\rborrowservice\"$\n\x11IsBorrowedRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"7\n\x13IsBorrowedByRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\")\n\x12IsBorrowedResponse\x12\x13\n\x0bis_borrowed\x18\x01 \x01(\x08\"1\n\rBorrowRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x05\"1\n\rReturnRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"\r\n\x0b\x45mptyObject2\xc9\x02\n\rBorrowService\x12R\n\x0bis_borrowed\x12 .borrowservice.IsBorrowedRequest\x1a!.borrowservice.IsBorrowedResponse\x12W\n\x0eis_borrowed_by\x12\".borrowservice.IsBorrowedByRequest\x1a!.borrowservice.IsBorrowedResponse\x12\x42\n\x06\x62orrow\x12\x1c.borrowservice.BorrowRequest\x1a\x1a.borrowservice.EmptyObject\x12G\n\x0breturn_book\x12\x1c.borrowservice.ReturnRequest\x1a\x1a.borrowservice.EmptyObjectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'borrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISBORROWEDREQUEST']._serialized_start=31
  _globals['_ISBORROWEDREQUEST']._serialized_end=67
  _globals['_ISBORROWEDBYREQUEST']._serialized_start=69
  _globals['_ISBORROWEDBYREQUEST']._serialized_end=124
  _globals['_ISBORROWEDRESPONSE']._serialized_start=126
  _globals['_ISBORROWEDRESPONSE']._serialized_end=167
  _globals['_BORROWREQUEST']._serialized_start=169
  _globals['_BORROWREQUEST']._serialized_end=218
  _globals['_RETURNREQUEST']._serialized_start=220
  _globals['_RETURNREQUEST']._serialized_end=269
  _globals['_EMPTYOBJECT']._serialized_start=271
  _globals['_EMPTYOBJECT']._serialized_end=284
  _globals['_BORROWSERVICE']._serialized_start=287
  _globals['_BORROWSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
