# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x0c\x62ooksservice\" \n\rIsBookRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"%\n\x12GetBookByIdRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\" \n\x0eIsBookResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"5\n\x10\x41llBooksResponse\x12!\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x12.booksservice.Book\"4\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\"c\n\x11UpdateBookRequest\x12 \n\x04\x62ook\x18\x01 \x01(\x0b\x32\x12.booksservice.Book\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\"\r\n\x0b\x45mptyObject2\xa8\x03\n\x0c\x42ooksService\x12\x44\n\x07is_book\x12\x1b.booksservice.IsBookRequest\x1a\x1c.booksservice.IsBookResponse\x12\x46\n\x0eget_book_by_id\x12 .booksservice.GetBookByIdRequest\x1a\x12.booksservice.Book\x12\x46\n\tall_books\x12\x19.booksservice.EmptyObject\x1a\x1e.booksservice.AllBooksResponse\x12\x39\n\x08\x61\x64\x64_book\x12\x12.booksservice.Book\x1a\x19.booksservice.EmptyObject\x12I\n\x0bupdate_book\x12\x1f.booksservice.UpdateBookRequest\x1a\x19.booksservice.EmptyObject\x12<\n\x0b\x64\x65lete_book\x12\x12.booksservice.Book\x1a\x19.booksservice.EmptyObjectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISBOOKREQUEST']._serialized_start=29
  _globals['_ISBOOKREQUEST']._serialized_end=61
  _globals['_GETBOOKBYIDREQUEST']._serialized_start=63
  _globals['_GETBOOKBYIDREQUEST']._serialized_end=100
  _globals['_ISBOOKRESPONSE']._serialized_start=102
  _globals['_ISBOOKRESPONSE']._serialized_end=134
  _globals['_ALLBOOKSRESPONSE']._serialized_start=136
  _globals['_ALLBOOKSRESPONSE']._serialized_end=189
  _globals['_BOOK']._serialized_start=191
  _globals['_BOOK']._serialized_end=243
  _globals['_UPDATEBOOKREQUEST']._serialized_start=245
  _globals['_UPDATEBOOKREQUEST']._serialized_end=344
  _globals['_EMPTYOBJECT']._serialized_start=346
  _globals['_EMPTYOBJECT']._serialized_end=359
  _globals['_BOOKSSERVICE']._serialized_start=362
  _globals['_BOOKSSERVICE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
